import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readdirSync, readFileSync, statSync} from 'node:fs';
import {join, extname, relative, sep} from 'node:path';

const DOCS = new URL('../docs/', import.meta.url).pathname;
const SIDEBARS = new URL('../sidebars.ts', import.meta.url).pathname;

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return ['.md', '.mdx'].includes(extname(full)) ? [full] : [];
  });
}

const sidebar = readFileSync(SIDEBARS, 'utf8');

// Directories covered by an `autogenerated` entry need no explicit listing.
const autoDirs = [...sidebar.matchAll(/dirName:\s*'([^']+)'/g)].map((m) => m[1]);

test('every doc is reachable from the sidebar', () => {
  const unreferenced = [];
  for (const file of walk(DOCS)) {
    const rel = relative(DOCS, file).split(sep).join('/');
    const id = rel.replace(/\.mdx?$/, '');
    if (autoDirs.some((d) => id.startsWith(`${d}/`))) continue;
    if (sidebar.includes(`'${id}'`)) continue;
    unreferenced.push(rel);
  }
  assert.deepEqual(
    unreferenced,
    [],
    `these docs are not in the sidebar and will be invisible in navigation:\n${unreferenced.join('\n')}`,
  );
});

test('every autogenerated dirName exists on disk', () => {
  for (const dir of autoDirs) {
    assert.ok(
      statSync(join(DOCS, dir)).isDirectory(),
      `sidebars.ts references dirName '${dir}', which does not exist under docs/`,
    );
  }
});
