import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Course navigation.
 *
 * Order here is the order learners see. A new page under `docs/` must be
 * registered below, or it builds and is reachable by URL but never appears
 * in the sidebar. `tests/sidebar.test.mjs` enforces that.
 */
const sidebars: SidebarsConfig = {
  courseSidebar: [
    'intro',
    'proven-practices',
    'reference',
    {
      type: 'category',
      label: 'Augmented Product Development Lab',
      collapsible: true,
      collapsed: false,
      items: [
        'part-2/overview',
        {
          type: 'category',
          label: 'Round 1: MVP',
          collapsible: true,
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'part-2/round-1'}],
        },
        {
          type: 'category',
          label: 'Round 2: Advanced',
          collapsible: true,
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'part-2/round-2'}],
        },
        {
          type: 'category',
          label: 'Round 3: Precision & Automation',
          collapsible: true,
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'part-2/round-3'}],
        },
        'part-2/agent-ready-repo',
      ],
    },
    {
      type: 'category',
      label: 'Setup & Installation',
      collapsible: true,
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'setup'}],
    },
  ],
};

export default sidebars;
